'use client';
import { useEffect, useState, type FormEvent } from 'react';
import Link from 'next/link';
import { ArrowRight, ArrowUpRight, BookOpen, Headphones, Layers3, Plus, LogOut, LoaderCircle } from 'lucide-react';
import { api, post, type Session } from '@/lib/learning';
import { currentUser, signIn, signOut, signUp } from '@/lib/auth';
import { Header, Footer, Constellation } from './Chrome';
export function Home() {
  const [user,setUser]=useState<{email:string}|null>(null), [sessions,setSessions]=useState<Session[]>([]), [loading,setLoading]=useState(true), [busy,setBusy]=useState(false), [error,setError]=useState(''), [register,setRegister]=useState(true);
  useEffect(()=>{currentUser().then(async u=>{setUser(u);setSessions(await api<Session[]>('/sessions'));}).catch(()=>{}).finally(()=>setLoading(false));},[]);
  async function authenticate(e:FormEvent<HTMLFormElement>) {e.preventDefault();setBusy(true);setError(''); const data=new FormData(e.currentTarget);try {const email=String(data.get('email')||'');const password=String(data.get('password')||'');setUser(register?await signUp(email,password):await signIn(email,password));setSessions(await api('/sessions'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function create() {setBusy(true);setError('');try {const s=await post<Session>('/sessions',{title:'Untitled learning space'});window.location.assign(`/documents/${s.id}`);}catch(e){setError((e as Error).message);setBusy(false);}}
  return <><Header>{user?<><a href="#library">Your spaces</a><button className="icon-button" aria-label="Sign out" onClick={async()=>{try{await signOut();setUser(null);setSessions([]);}catch(e){setError((e as Error).message);}}}><LogOut size={17}/></button></>:undefined}</Header><main id="main">
    <section className="hero wrap"><div className="hero-copy"><span className="eyebrow"><i/> YOUR CURIOSITY. CONNECTED.</span><h1>Your material.<br/>A whole new<br/><em>understanding.</em></h1><p>Turn your notes, textbooks, and slides into a conversation. Learn at your pace. Ask the next question. Make it yours.</p><a className="button hero-cta" href={user?'#library':'#start'}>{user?'Open your learning spaces':'Create your learning space'} <ArrowUpRight size={17}/></a><span className="hero-note">Built from your sources. Shaped around you.</span></div><Constellation/></section>
    <section className="workflow wrap" id="how"><div className="section-heading"><div><span className="eyebrow">LESS RE-READING. MORE UNDERSTANDING.</span><h2>From information<br/>to your next “aha.”</h2></div><p>A focused space for the material you actually need to learn. No preset subjects. No noise.</p></div><div className="steps">{[{n:'01',icon:Layers3,title:'Bring your material',text:'Add documents or paste your notes. Your learning space starts with what matters to you.'},{n:'02',icon:Headphones,title:'Talk it through',text:'Explore connected concepts with a tutor. Ask questions, follow sources, and find a clearer explanation.'},{n:'03',icon:BookOpen,title:'Make it stick',text:'Practice what you learned. See where you are confident and what deserves another look.'}].map(s=><article key={s.n}><div className="step-top"><span>{s.n}</span><s.icon size={20}/></div><h3>{s.title}</h3><p>{s.text}</p></article>)}</div><div className="signal-line" aria-hidden="true"><svg viewBox="0 0 1100 65" preserveAspectRatio="none"><defs><linearGradient id="signal"><stop stopColor="#8052ff"/><stop offset=".5" stopColor="#78d8be"/><stop offset="1" stopColor="#ffb829"/></linearGradient></defs><path d="M0 38C130 -15 210 68 380 34S570 -6 710 35 930 70 1100 10" stroke="url(#signal)" fill="none"/></svg></div></section>
    <section className="start-section wrap" id={user?'library':'start'}><div className="section-heading"><div><span className="eyebrow">YOUR PERSONAL LEARNING UNIVERSE</span><h2>{user?'Pick up your curiosity.':'Your next chapter\nstarts here.'}</h2></div><p>{user?'Everything you upload and discover, together in your private spaces.':'Create an account to keep your documents, conversations, and progress together.'}</p></div>{error&&<p className="error" role="alert">{error}</p>}{loading?<p className="muted status-line"><LoaderCircle className="spin" size={17}/> Opening your space…</p>:user?<><div className="library-bar"><span className="muted">Signed in as {user.email}</span><button className="button" disabled={busy} onClick={create}><Plus size={17}/> New learning space</button></div>{sessions.length?<div className="session-grid">{sessions.map(s=><Link href={`/documents/${s.id}`} className="session-card" key={s.id}><div className="card-top"><Layers3 size={22}/><ArrowUpRight size={18}/></div><h3>{s.title}</h3><p>{s.files?.length||0} sources · {s.concepts?.length||0} concepts</p><span className={`status-badge ${s.status==='ERROR'?'warning':''}`}>{s.status.toLowerCase()}</span></Link>)}</div>:<div className="empty-space"><Layers3 size={30}/><h3>A blank space. Endless possibilities.</h3><p>No material yet. Create a space and upload your first source to start learning.</p></div>}</>:<div className="auth-layout"><div className="auth-copy"><span className="tiny-tag">SOURCE FIRST · ALWAYS</span><h3>Not another pile<br/>of summaries.</h3><p>A place to work through difficult ideas, connect the dots, and find out what you really understand.</p></div><form className="auth-form" onSubmit={authenticate}><div className="segmented" aria-label="Account action"><button type="button" className={register?'active':''} onClick={()=>{setRegister(true);setError('');}}>Create account</button><button type="button" className={!register?'active':''} onClick={()=>{setRegister(false);setError('');}}>Sign in</button></div><label htmlFor="email">Email address</label><input id="email" name="email" type="email" placeholder="you@example.com" autoComplete="email" required/><label htmlFor="password">Password</label><input id="password" name="password" type="password" minLength={8} placeholder="At least 8 characters" autoComplete={register?'new-password':'current-password'} required/><button className="button" disabled={busy}>{busy?<LoaderCircle size={17} className="spin"/>:null}{register?'Create your account':'Welcome back'}<ArrowRight size={17}/></button><p className="form-note">Your material stays in your account. You choose what to upload.</p></form></div>}</section>
  </main><Footer/></>;
}
