'use client';
import { useState, useEffect, useCallback, type FormEvent } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, Upload, FileText, Trash2, Sparkles, Send, LoaderCircle, Check, BookOpen, Target, ChartNoAxesCombined, RefreshCw, Download, Plus } from 'lucide-react';
import { api, post, API, type Session, type Question, type Answer, type Report, type Citation } from '@/lib/learning';
import { Header, Footer } from './Chrome';
import { LiveVoice } from './LiveVoice';
function Sources({citations}:{citations?:Citation[]}) {return citations?.length?<div className="citations">{citations.map((c,i)=><details key={i}><summary><FileText size={12}/>{c.filename}{c.page?` · p. ${c.page}`:''}</summary><p>{c.text}</p></details>)}</div>:null;}
export function Workspace({id}:{id:string}) {
 const [session,setSession]=useState<Session|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(''),[mode,setMode]=useState('learn'),[concept,setConcept]=useState(''),[message,setMessage]=useState(''),[notes,setNotes]=useState(''),[showNotes,setShowNotes]=useState(false),[question,setQuestion]=useState<Question|null>(null),[answer,setAnswer]=useState(''),[result,setResult]=useState<Answer|null>(null),[report,setReport]=useState<Report|null>(null),[finalMode,setFinalMode]=useState(false);
 const refreshSession=useCallback(async()=>{const s=await api<Session>(`/sessions/${id}`);setSession(s);},[id]);
 useEffect(()=>{refreshSession().catch(e=>setError(e.message));},[refreshSession]);
 useEffect(()=>{if(session?.status!=='PROCESSING')return;const timer=setInterval(()=>refreshSession().catch(e=>setError(e.message)),1800);return()=>clearInterval(timer);},[session?.status,refreshSession]);
 async function run(name:string,action:()=>Promise<void>){setBusy(name);setError('');try{await action();}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 async function upload(files:File[]){if(!files.length)return;await run('upload',async()=>{const data=new FormData();files.forEach(f=>data.append('files',f));await api(`/sessions/${id}/files`,{method:'POST',body:data});await refreshSession();setNotes('');setShowNotes(false);});}
 async function ask(e:FormEvent){e.preventDefault();if(!message.trim())return;await run('chat',async()=>{await post(`/sessions/${id}/chat`,{message:message.trim(),concept_id:concept||undefined});setMessage('');await refreshSession();});}
 async function nextQuestion(final=finalMode){await run('question',async()=>{const q=await post<Question>(`/sessions/${id}/quiz`,{concept_id:concept||undefined,final});setQuestion(q);setAnswer('');setResult(null);setFinalMode(final);});}
 async function loadReport(){setMode('report');await run('report',async()=>setReport(await api<Report>(`/sessions/${id}/report`)));}
 if(!session)return <><Header/><main id="main" className="wrap loading-page">{error?<div className="error" role="alert"><p>{error}</p><Link href="/" className="button secondary">Back to sign in</Link><button className="button secondary" onClick={()=>run('load',refreshSession)}>Try again</button></div>:<p className="status-line"><LoaderCircle className="spin" size={20}/> Opening your learning space…</p>}</main></>;
 const ready=session.status==='READY'; const selected=session.concepts.find(c=>c.id===concept);
 return <><Header><Link href="/">All spaces <ArrowLeft size={15}/></Link><span className="private-badge">PRIVATE SPACE</span></Header><main id="main" className="workspace wrap"><div className="workspace-heading"><div><span className="eyebrow">YOUR MATERIAL. YOUR MOMENTUM.</span><h1>{session.title}</h1><p>{session.files.length} source{session.files.length===1?'':'s'} · {session.concepts.length} connected concepts</p></div><button className="icon-button danger" title="Delete this learning space" aria-label="Delete this learning space" disabled={!!busy} onClick={()=>{if(window.confirm('Delete this space, its sources, and learning history? This cannot be undone.'))run('delete',async()=>{await api(`/sessions/${id}`,{method:'DELETE'});window.location.assign('/');});}}><Trash2 size={18}/></button></div>{error&&<div className="error" role="alert">{error}</div>}{session.error&&<div className="error" role="alert">{session.error}</div>}
 <div className="workspace-grid"><aside className="source-panel"><div className="panel-heading"><h2>Your sources</h2><span className="count">{session.files.length}</span></div><label className={`upload-zone ${busy?'disabled':''}`}><Upload size={24}/><strong>{busy==='upload'?'Uploading…':'Add your material'}</strong><span>Choose files or drop them here</span><small>PDF, DOCX, PPTX, TXT, MD, images</small><input aria-label="Upload learning material" type="file" multiple accept=".pdf,.doc,.docx,.ppt,.pptx,.txt,.md,.png,.jpg,.jpeg,.webp" disabled={!!busy||session.status==='PROCESSING'} onChange={e=>{upload(Array.from(e.target.files||[]));e.target.value='';}}/></label><button className="button secondary full" onClick={()=>setShowNotes(!showNotes)}><Plus size={15}/>{showNotes?'Close notes':'Paste your notes'}</button>{showNotes&&<form className="notes-form" onSubmit={e=>{e.preventDefault();upload([new File([notes],'My notes.txt',{type:'text/plain'})]);}}><label htmlFor="notes">Your notes</label><textarea id="notes" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Paste the material you want to learn…" required rows={7}/><button className="button small" disabled={!!busy||!notes.trim()}>Add notes <ArrowRight size={14}/></button></form>}
 <ul className="file-list">{session.files.map(f=><li key={f.id}><FileText size={17}/><div><strong>{f.name}</strong><span>{f.error||`${f.status.toLowerCase()}${f.pages?` · ${f.pages} pages`:''}`}</span></div><button className="icon-button" aria-label={`Remove ${f.name}`} disabled={!!busy||session.status==='PROCESSING'} onClick={()=>run('remove',async()=>{await api(`/sessions/${id}/files/${f.id}`,{method:'DELETE'});await refreshSession();setQuestion(null);setReport(null);})}><Trash2 size={14}/></button></li>)}</ul>
 {session.files.length>0&&<button className="button full" disabled={!!busy||session.status==='PROCESSING'} onClick={()=>run('analyze',async()=>{await post(`/sessions/${id}/analyze`);await refreshSession();setQuestion(null);setReport(null);})}>{session.status==='PROCESSING'||busy==='analyze'?<LoaderCircle className="spin" size={16}/>:<Sparkles size={16}/>} {session.status==='PROCESSING'?'Connecting your material…':ready?'Refresh knowledge map':'Analyze your material'}</button>}<p className="source-note">Teaching starts with your sources. Add or replace material, then analyze it to update your learning map.</p>
 </aside><section className="learning-panel">{!ready?<div className="workspace-empty"><div className="empty-orbit"><Sparkles size={28}/></div><span className="eyebrow">{session.status==='PROCESSING'?'CONNECTING THE DOTS':'A SPACE FOR YOUR NEXT AHA'}</span><h2>{session.status==='PROCESSING'?'Finding the ideas\ninside your material.':'Your knowledge\nstarts here.'}</h2><p>{session.status==='PROCESSING'?'We are extracting your sources and building your concept map. You can leave this space and return when it is ready.':'Upload your material to begin learning. Your concepts, conversations, and practice will grow from what you add.'}</p>{session.status==='PROCESSING'&&<LoaderCircle className="spin" size={23}/>}</div>:<>
 <div className="mode-tabs" role="tablist" aria-label="Learning mode">{[{id:'learn',name:'Learn',icon:BookOpen},{id:'practice',name:'Practice',icon:Target},{id:'report',name:'Your progress',icon:ChartNoAxesCombined}].map(t=><button key={t.id} role="tab" aria-selected={mode===t.id} className={mode===t.id?'active':''} onClick={()=>t.id==='report'?loadReport():setMode(t.id)}><t.icon size={17}/>{t.name}</button>)}</div>
 <div className="concept-section"><div className="panel-heading"><div><span className="eyebrow">CONNECTED TO YOUR SOURCES</span><h2>Your knowledge map</h2></div><button className="text-button" onClick={()=>setConcept('')}>All concepts</button></div><div className="concept-list">{session.concepts.map((c,i)=><button key={c.id} className={`concept ${concept===c.id?'selected':''}`} onClick={()=>{setConcept(c.id);setQuestion(null);setResult(null);}}><span className="concept-number">{String(i+1).padStart(2,'0')}</span><span><strong>{c.title}</strong><small>{c.mastery===null?'Not assessed':`${Math.round(c.mastery<=1?c.mastery*100:c.mastery)}% estimated mastery`} · {c.state.toLowerCase().replaceAll('_',' ')}</small></span>{c.state==='MASTERED'?<Check size={15}/>:<span className="concept-dot"/>}</button>)}</div>{selected&&<div className="concept-detail"><p>{selected.summary}</p>{selected.prerequisites?.length>0&&<small>Connects to: {selected.prerequisites.map(p=>session.concepts.find(c=>c.id===p)?.title||p).join(' · ')}</small>}</div>}</div>
 {mode==='learn'&&<div className="learn-content"><div className="panel-heading"><h2>Let’s work it through.</h2><span className="tiny-tag">SOURCE GROUNDED</span></div><LiveVoice sessionId={session.id} onTranscript={()=>refreshSession()}/><div className="conversation" aria-live="polite">{session.messages.length?session.messages.map((m,i)=><article key={i} className={`message ${m.role==='user'?'user':'tutor'}`}><span className="message-label">{m.role==='user'?'YOU':'LEARNOVA'}</span><p>{m.content}</p><Sources citations={m.citations}/></article>):<div className="conversation-empty"><p>Start with a question. Follow a concept. Make room for understanding.</p><button className="button secondary" onClick={()=>setMessage(selected?`Teach me ${selected.title}, one step at a time.`:'Help me understand the first concept in my material, one step at a time.')}>Help me get started <ArrowRight size={14}/></button></div>}{busy==='chat'&&<p className="status-line muted"><LoaderCircle className="spin" size={15}/> Checking your sources…</p>}</div><form className="composer" onSubmit={ask}><label className="sr-only" htmlFor="message">Ask about your material</label><textarea id="message" value={message} onChange={e=>setMessage(e.target.value)} placeholder={selected?`Ask about ${selected.title}…`:'Ask anything about your material…'} rows={2} required/><button className="button" type="submit" disabled={!!busy||!message.trim()} aria-label="Send question"><Send size={18}/></button></form><p className="form-note">AI can make mistakes. Open source references to verify important details.</p></div>}
 {mode==='practice'&&<div className="practice-content"><span className="eyebrow">RECALL. REFLECT. REPEAT.</span><h2>A little practice.<br/>A clearer picture.</h2><p className="muted">Questions come from your material. Your answers guide what to practice next.</p>{!question?<div className="practice-actions"><button className="button" disabled={!!busy} onClick={()=>nextQuestion(false)}><Target size={17}/> Start practice</button><button className="button secondary" disabled={!!busy} onClick={()=>nextQuestion(true)}>Final assessment <ArrowRight size={16}/></button></div>:<form className="question-card" onSubmit={e=>{e.preventDefault();run('answer',async()=>{setResult(await post<Answer>(`/sessions/${id}/answers`,{question_id:question.id,answer}));await refreshSession();});}}><span className="tiny-tag">{finalMode?'FINAL ASSESSMENT':'ADAPTIVE PRACTICE'} · LEVEL {question.difficulty}</span><h3>{question.prompt}</h3>{question.options?.length?<fieldset disabled={!!result||!!busy}><legend className="sr-only">Choose an answer</legend>{question.options.map((o,i)=><label className={`answer-option ${answer===o?'chosen':''}`} key={i}><input type="radio" name="answer" value={o} checked={answer===o} onChange={()=>setAnswer(o)} required/><span>{o}</span></label>)}</fieldset>:<><label htmlFor="answer">Explain in your own words</label><textarea id="answer" value={answer} onChange={e=>setAnswer(e.target.value)} disabled={!!result} required rows={4}/></>}{!result?<button className="button" disabled={!!busy||!answer.trim()}>Check understanding <ArrowRight size={16}/></button>:<div className={`answer-feedback ${result.correct?'correct':''}`} aria-live="polite"><strong>{result.correct?'You’ve got it.':'Let’s revisit this idea.'}</strong><p>{result.feedback}</p><p>{result.explanation}</p><p className="muted">{result.next_step}</p><button type="button" className="button" disabled={!!busy} onClick={()=>nextQuestion()}>Next question <ArrowRight size={16}/></button><button type="button" className="text-button" onClick={loadReport}>See my progress</button></div>}</form>}{busy==='question'&&<p className="status-line"><LoaderCircle className="spin" size={18}/> Preparing a question from your sources…</p>}</div>}
 {mode==='report'&&<div className="report-content"><div className="panel-heading"><div><span className="eyebrow">EVIDENCE, NOT GUESSWORK</span><h2>Your learning, in focus.</h2></div><button className="icon-button" aria-label="Refresh progress" onClick={loadReport}><RefreshCw size={17}/></button></div>{report?<><div className="report-stats"><div><strong>{report.answered?`${Math.round(report.percentage)}%`:'—'}</strong><span>Assessment score</span></div><div><strong>{report.answered||0}</strong><span>Answers recorded</span></div><div><strong>{report.strong?.length||0}</strong><span>Strong concepts</span></div></div>{!report.answered&&<p className="muted">Not assessed yet. Complete practice questions to build an evidence-based picture of your understanding.</p>}<div className="report-columns"><div><h3>Coming together</h3>{report.strong?.length?report.strong.map(s=><p key={s} className="positive">{s}</p>):<p className="muted">More practice will reveal your strengths.</p>}</div><div><h3>Worth another look</h3>{report.weak?.length?report.weak.map(s=><p key={s}>{s}</p>):<p className="muted">No weak concepts identified yet.</p>}</div></div><div className="next-step"><span className="eyebrow">YOUR NEXT STEP</span><p>{report.next_step}</p></div><a className="button secondary" href={`${API}/sessions/${id}/report.pdf`} target="_blank" rel="noreferrer"><Download size={16}/> Download learning report</a></>:<p className="muted">{busy==='report'?'Loading your learning evidence…':'Progress could not be loaded. Please retry.'}</p>}</div>}
 </>}</section></div></main><Footer/></>;
}
